export const PROBLEMS = [
    {
        id: 1,
        name: "Two Sum",
        difficulty: "Easy",
        notes: "Use a hashmap to track the complement of each number.",
        is_solved: true,
    },
    {
        id: 2,
        name: "Add Two Numbers",
        difficulty: "Medium",
        notes: "Remember to handle carry over for digits summing more than 9.",
        is_solved: false,
    },
    {
        id: 3,
        name: "Longest Substring Without Repeating Characters",
        difficulty: "Medium",
        notes: "Sliding window can efficiently solve this problem.",
        is_solved: true,
    },
    {
        id: 4,
        name: "Median of Two Sorted Arrays",
        difficulty: "Hard",
        notes: "Binary search can be applied to find the median in logarithmic time.",
        is_solved: false,
    },
    {
        id: 5,
        name: "Longest Palindromic Substring",
        difficulty: "Medium",
        notes: "Expand around center can solve it in O(n^2) time.",
        is_solved: true,
    },
    {
        id: 6,
        name: "ZigZag Conversion",
        difficulty: "Medium",
        notes: "The key is to find the pattern of the indices.",
        is_solved: false,
    },
    {
        id: 7,
        name: "Reverse Integer",
        difficulty: "Easy",
        notes: "Watch out for overflow when reversing.",
        is_solved: true,
    },
];